service: savour-text-service-api

package:
  individually: true

plugins:
  - serverless-bundle 
  - serverless-offline
  # - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  environment:
    businessTable: !ImportValue '${self:provider.stage}-Businesses-TableName'
    businessUserTable: !ImportValue '${self:provider.stage}-BusinessUsers-TableName'
    subscriberUserTable: !ImportValue '${self:provider.stage}-SubscriberUsers-TableName'
    pushMessageTable: !ImportValue '${self:provider.stage}-PushMessage-TableName'
    # unclaimedButtonTable: !ImportValue '${self:provider.stage}-UnclaimedButton-TableName'
    redirectTable: !ImportValue '${self:provider.stage}-Redirect-TableName'
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
        - ssm:GetParameter
      Resource: "*"
functions:

  ######################################################
  #####                                            #####
  #####          businesses table API              #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /businesses
  # - method: POST request
  create-business:
    handler: src/businesses/index.create
    events:
      - http:
          path: businesses
          method: post
          cors: true
          authorizer: aws_iam
  get-business:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /businesses/{id}
    # - method: GET request
    handler: src/businesses/index.get
    events:
      - http:
          path: businesses/{place_id}
          method: get
          cors: true
          authorizer: aws_iam
  update-business:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /businesses/{place_id}
    # - method: PUT request
    handler: src/businesses/index.update
    events:
      - http:
          path: businesses/{place_id}
          method: put
          cors: true
          authorizer: aws_iam
  delete-business:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /businesses/{place_id}
    # - method: DELETE request
    handler: src/businesses/index.del
    events:
      - http:
          path: businesses/{place_id}
          method: delete
          cors: true
          authorizer: aws_iam

  ######################################################
  #####                                            #####
  #####          business users table API          #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /business_users
  # - method: POST request
  create-business-user:
    handler: src/business_users/index.create
    events:
      - http:
          path: business_users
          method: post
          cors: true
          authorizer: aws_iam
  get-business-user:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is business_users/{uid}
    # - method: GET request
    handler: src/business_users/index.get
    events:
      - http:
          path: business_users/{uid}
          method: get
          cors: true
          authorizer: aws_iam
  update-business-user:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is business_users/{uid}
    # - method: PUT request
    handler: src/business_users/index.update
    events:
      - http:
          path: business_users/{uid}
          method: put
          cors: true
          authorizer: aws_iam
  delete-business-user:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is business_users/{uid}
    # - method: DELETE request
    handler: src/business_users/index.del
    events:
      - http:
          path: business_users/{uid}
          method: delete
          cors: true
          authorizer: aws_iam

  ######################################################
  #####                                            #####
  #####          subscriber users table API        #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /subscriber_users
  # - method: POST request
  create-subscriber-user:
    handler: src/subscriber_users/index.create
    events:
      - http:
          path: subscriber_users
          method: post
          cors: true
          authorizer: aws_iam
  get-subscriber-user:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is subscriber_users/{mobile_number}
    # - method: GET request
    handler: src/subscriber_users/index.get
    events:
      - http:
          path: subscriber_users/{mobile_number}
          method: get
          cors: true
          authorizer: aws_iam
  update-subscriber-user:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is subscriber_users/{mobile_number}
    # - method: PUT request
    handler: src/subscriber_users/index.update
    events:
      - http:
          path: subscriber_users/{mobile_number}
          method: put
          cors: true
          authorizer: aws_iam
  delete-subscriber-user:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is subscriber_users/{mobile_number}
    # - method: DELETE request
    handler: src/subscriber_users/index.del
    events:
      - http:
          path: subscriber_users/{mobile_number}
          method: delete
          cors: true
          authorizer: aws_iam
  
  ######################################################
  #####                                            #####
  #####              push table API                #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /push_table
  # - method: POST request
  create-push-table:
    handler: src/push_table/index.create
    events:
      - http:
          path: push_table
          method: post
          cors: true
          authorizer: aws_iam
  get-push-table:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is push_table/{uid}
    # - method: GET request
    handler: src/push_table/index.get
    events:
      - http:
          path: push_table/g/{uid}
          method: get
          cors: true
          authorizer: aws_iam
  get-all-push-table:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is push_table/{btn_id}
    # - method: GET request
    handler: src/push_table/index.getAll
    events:
      - http:
          path: push_table/q/{btn_id}
          method: get
          cors: true
          authorizer: aws_iam
  delete-push-table:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is push_table/{uid}
    # - method: DELETE request
    handler: src/push_table/index.del
    events:
      - http:
          path: push_table/{uid}
          method: delete
          cors: true
          authorizer: aws_iam

  ######################################################
  #####                                            #####
  #####       message service API                  #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in twilio-hooks.js
  # - path: url path is /message_service/twilio_hooks
  # - method: POST request
  twilio-hooks:
    handler: src/message_service/index.hooks
    events:
      - http:
          path: message_service/twilio_hooks
          method: post
          cors: true
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              application/x-www-form-urlencoded: ${file(message_service/twilio-request.vtl)}
          response:
            statusCodes:
              200:
                headers:
                  Content-Type: "'application/xml'"
                pattern: ""
                template:
                  application/xml: ${file(message_service/twilio-response.vtl)}
  send-message:
    handler: src/message_service/index.sendMessage
    events:
      - http:
          path: message_service/send_message
          method: post
          cors: true
  # Defines an HTTP API endpoint that calls the main function in button-service.js
  # - path: url path is /message_service/button-service
  # - method: POST request
  button-service: 
    handler: src/message_service/index.buttonService
    environment: 
      uuidSize: ${file(./env/config.${self:provider.stage}.json):uuidSize}
      accountSid: ${ssm:/twilio/accountSid~true}
      authToken: ${ssm:/twilio/authToken~true}
    events:
      - http:
          path: message_service/button-service
          method: post
          cors: true
  # Defines an HTTP API endpoint that calls the main function in create-twilio-number.js
  # - path: url path is /message_service/twilio_number/{place_id}
  # - method: POST request
  create-twilio-number:
    handler: src/message_service/index.createNumber
    environment: 
      uuidSize: ${file(./env/config.${self:provider.stage}.json):uuidSize}
      accountSid: ${ssm:/twilio/accountSid~true}
      authToken: ${ssm:/twilio/authToken~true}
      twilioWebhookUrl: ${ssm:/twilio/webhook/${self:provider.stage}~true}
    events:
      - http:
          path: message_service/twilio_number/{place_id}
          method: post
          cors: true

  ######################################################
  #####                                            #####
  #####       Payment Service API                  #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /payments/{place_id}
  # - method: POST request
  create-customer:
    handler: src/payment/index.cancelSubscription
    environment: 
      stripeKey: ${ssm:/stripeSecretKey/${self:provider.stage}~true}
      recurringPlanID: ${file(./env/config.${self:provider.stage}.json):recurringPlanID}
      usagePlanID: ${file(./env/config.${self:provider.stage}.json):usagePlanID}
    events:
      - http:
          path: payments/{place_id}
          method: post
          cors: true
  # Defines an HTTP API endpoint that calls the main function in update-card.js
  # - path: url path is /payments/card/{place_id}
  # - method: PUT request
  update-card:
    handler: src/payment/index.updateCard
    environment: 
      stripeKey: ${ssm:/stripeSecretKey/${self:provider.stage}~true}
    events:
      - http:
          path: payments/card/{place_id}
          method: put
          cors: true
  # Defines an HTTP API endpoint that calls the main function in update-usage.js
  # - path: url path is /payments/usage/{place_id}
  # - method: PUT request
  update-usage:
    handler: src/payment/index.updateUsage
    environment: 
      stripeKey: ${ssm:/stripeSecretKey/${self:provider.stage}~true}
    events:
      - http:
          path: payments/usage/{place_id}
          method: put
          cors: true
  # Defines an HTTP API endpoint that calls the main function in cancel-subscription.js
  # - path: url path is /payments/subscription/{place_id}
  # - method: DELETE request
  cancel-subscription:
    handler: src/payment/index.cancelSubscription
    environment: 
      stripeKey: ${ssm:/stripeSecretKey/${self:provider.stage}~true}
    events:
      - http:
          path: payments/subscription/{place_id}
          method: delete
          cors: true

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)} 