# NOTE: update this with your service name
service: savour-button-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    businessesTbl: businesses
    businesUsersTbl: business_users
    subscriberUsersTbl: subscriber_users
    pushTbl: push_table

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /business
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role

  ######################################################
  #####                                            #####
  #####          businesses table API              #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /businesses
  # - method: POST request
  create-business:
    handler: businesses_API/create.main
    events:
      - http:
          path: businesses
          method: post
          cors: true
          authorizer: aws_iam
  get-business:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /businesses/{id}
    # - method: GET request
    handler: businesses_API/get.main
    events:
      - http:
          path: businesses/{place_id}
          method: get
          cors: true
          authorizer: aws_iam
  update-business:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /businesses/{place_id}
    # - method: PUT request
    handler: businesses_API/update.main
    events:
      - http:
          path: businesses/{place_id}
          method: put
          cors: true
          authorizer: aws_iam
  delete-business:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /businesses/{place_id}
    # - method: DELETE request
    handler: businesses_API/delete.main
    events:
      - http:
          path: businesses/{place_id}
          method: delete
          cors: true
          authorizer: aws_iam

  ######################################################
  #####                                            #####
  #####          business users table API          #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /business_users
  # - method: POST request
  create-business-user:
    handler: business_users_API/create.main
    events:
      - http:
          path: business_users
          method: post
          cors: true
          authorizer: aws_iam
  get-business-user:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is business_users/{uid}
    # - method: GET request
    handler: business_users_API/get.main
    events:
      - http:
          path: business_users/{uid}
          method: get
          cors: true
          authorizer: aws_iam
  update-business-user:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is business_users/{uid}
    # - method: PUT request
    handler: business_users_API/update.main
    events:
      - http:
          path: business_users/{uid}
          method: put
          cors: true
          authorizer: aws_iam
  delete-business-user:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is business_users/{uid}
    # - method: DELETE request
    handler: business_users_API/delete.main
    events:
      - http:
          path: business_users/{uid}
          method: delete
          cors: true
          authorizer: aws_iam

  ######################################################
  #####                                            #####
  #####          subscriber users table API        #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /subscriber_users
  # - method: POST request
  create-subscriber-user:
    handler: subscriber_users_API/create.main
    events:
      - http:
          path: subscriber_users
          method: post
          cors: true
          authorizer: aws_iam
  get-subscriber-user:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is subscriber_users/{mobile_number}
    # - method: GET request
    handler: subscriber_users_API/get.main
    events:
      - http:
          path: subscriber_users/{mobile_number}
          method: get
          cors: true
          authorizer: aws_iam
  update-subscriber-user:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is subscriber_users/{mobile_number}
    # - method: PUT request
    handler: subscriber_users_API/update.main
    events:
      - http:
          path: subscriber_users/{mobile_number}
          method: put
          cors: true
          authorizer: aws_iam
  delete-subscriber-user:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is subscriber_users/{mobile_number}
    # - method: DELETE request
    handler: subscriber_users_API/delete.main
    events:
      - http:
          path: subscriber_users/{mobile_number}
          method: delete
          cors: true
          authorizer: aws_iam
  
  ######################################################
  #####                                            #####
  #####              push table API                #####
  #####                                            #####
  ######################################################
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /push_table
  # - method: POST request
  create-push-table:
    handler: push_table_API/create.main
    events:
      - http:
          path: push_table
          method: post
          cors: true
          authorizer: aws_iam
  get-push-table:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is push_table/{uid}
    # - method: GET request
    handler: push_table_API/get.main
    events:
      - http:
          path: push_table/g/{uid}
          method: get
          cors: true
          authorizer: aws_iam
  get-all-push-table:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is push_table/{btn_id}
    # - method: GET request
    handler: push_table_API/get-all.main
    events:
      - http:
          path: push_table/q/{btn_id}
          method: get
          cors: true
          authorizer: aws_iam
  delete-push-table:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is push_table/{uid}
    # - method: DELETE request
    handler: push_table_API/delete.main
    events:
      - http:
          path: push_table/{uid}
          method: delete
          cors: true
          authorizer: aws_iam